name: dormease
description: "DormEase: Hostel and PG management app"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  easy_localization: ^3.0.7
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  fl_chart: ^0.68.0
  firebase_core: ^2.19.0
  firebase_auth: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/